[2023-11-22T23:23:45.690+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xml_parsing.parse_xml scheduled__2023-11-22T22:22:00+00:00 [queued]>
[2023-11-22T23:23:45.696+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xml_parsing.parse_xml scheduled__2023-11-22T22:22:00+00:00 [queued]>
[2023-11-22T23:23:45.696+0100] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2023-11-22T23:23:45.715+0100] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): parse_xml> on 2023-11-22 22:22:00+00:00
[2023-11-22T23:23:45.721+0100] {standard_task_runner.py:57} INFO - Started process 21902 to run task
[2023-11-22T23:23:45.725+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'xml_parsing', 'parse_xml', 'scheduled__2023-11-22T22:22:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/xml_parsing_DAG.py', '--cfg-path', '/tmp/tmp9071wb52']
[2023-11-22T23:23:45.726+0100] {standard_task_runner.py:85} INFO - Job 64: Subtask parse_xml
[2023-11-22T23:23:45.788+0100] {task_command.py:416} INFO - Running <TaskInstance: xml_parsing.parse_xml scheduled__2023-11-22T22:22:00+00:00 [running]> on host yzpt-Lenovo-ideapad-320S-14IKB
[2023-11-22T23:23:45.886+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='xml_parsing' AIRFLOW_CTX_TASK_ID='parse_xml' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T22:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-22T22:22:00+00:00'
[2023-11-22T23:23:45.887+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: parse_xml() missing 1 required positional argument: 'xml_file'
[2023-11-22T23:23:45.891+0100] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=xml_parsing, task_id=parse_xml, execution_date=20231122T222200, start_date=20231122T222345, end_date=20231122T222345
[2023-11-22T23:23:45.916+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 64 for task parse_xml (parse_xml() missing 1 required positional argument: 'xml_file'; 21902)
[2023-11-22T23:23:45.944+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:23:45.976+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
